app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


Route::resource('posts', 'PostsController');
Route::get('admin', array('as' => 'posts.admin', function()
{
	return View::make('posts.admin');
}));

Route::get('/', function()
{
	return View::make('hello');
});

app/filters.php
<?php

/*
|--------------------------------------------------------------------------
| Application & Route Filters
|--------------------------------------------------------------------------
|
| Below you will find the "before" and "after" events for the application
| which may be used to do any work before or after a request into your
| application. Here you may also register your custom route filters.
|
*/

App::before(function($request)
{
	//
});


App::after(function($request, $response)
{
	//
});

/*
|--------------------------------------------------------------------------
| Authentication Filters
|--------------------------------------------------------------------------
|
| The following filters are used to verify that the user of the current
| session is logged into this application. The "basic" filter easily
| integrates HTTP Basic authentication for quick, simple checking.
|
*/

Route::filter('auth', function()
{
	if (Auth::guest())
	{
		if (Request::ajax())
		{
			return Response::make('Unauthorized', 401);
		}
		else
		{
			return Redirect::guest('login');
		}
	}
});


Route::filter('auth.basic', function()
{
	return Auth::basic();
});

/*
|--------------------------------------------------------------------------
| Guest Filter
|--------------------------------------------------------------------------
|
| The "guest" filter is the counterpart of the authentication filters as
| it simply checks that the current user is not logged in. A redirect
| response will be issued if they are, which you may freely change.
|
*/

Route::filter('guest', function()
{
	if (Auth::check()) return Redirect::to('/');
});

/*
|--------------------------------------------------------------------------
| CSRF Protection Filter
|--------------------------------------------------------------------------
|
| The CSRF filter is responsible for protecting your application against
| cross-site request forgery attacks. If this special token in a user
| session does not match the one given in this request, we'll bail.
|
*/

Route::filter('csrf', function()
{
	if (Session::token() != Input::get('_token'))
	{
		throw new Illuminate\Session\TokenMismatchException;
	}
});

app/models/Post.php
<?php

class Post extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		// 'title' => 'required'
	];

	// Don't forget to fill this array
	protected $fillable = ['title', 'text', 'published_at', 'expired_at'];


	public function getDates()
	{
	    return array('created_at', 'updated_at', 'published_at', 'expired_at');
	}

}

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

}

app/controllers/BaseController.php
<?php

class BaseController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

app/controllers/HomeController.php
<?php

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

app/controllers/PostsController.php
<?php

class PostsController extends \BaseController {

	/**
	 * Display a listing of posts
	 *
	 * @return Response
	 */
	public function index()
	{
		$posts = Post::all();

		return View::make('posts.index', compact('posts'));
	}

	/**
	 * Show the form for creating a new post
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('posts.create');
	}

	/**
	 * Store a newly created post in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make($data = Input::all(), Post::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		Post::create($data);

		return Redirect::route('posts.admin');
	}

	/**
	 * Display the specified post.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$post = Post::findOrFail($id);

		return View::make('posts.show', compact('post'));
	}

	/**
	 * Show the form for editing the specified post.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$post = Post::find($id);

		return View::make('posts.edit', compact('post'));
	}

	/**
	 * Update the specified post in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$post = Post::findOrFail($id);

		$validator = Validator::make($data = Input::all(), Post::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		$post->update($data);

		return Redirect::route('posts.admin');
	}

	/**
	 * Remove the specified post from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Post::destroy($id);

		return Redirect::route('posts.admin');
	}

}

app/views/master.blade.php
<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>@yield('title', 'Presentation')</title>

		@section('styles')
		    {{ HTML::style('css/all.css') }}
		@show

		@section('scripts')
			{{HTML::script(url("//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"))}}
			{{HTML::script('//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')}}
			{{HTML::script(url("js/bootswatch.js"))}}
		@show

		@section('angular')	
		@show
	</head>

	@section('body')
		<body class="container">
			@include('navbar')
			<div class="panel panel-default">
		  		<div class="panel-body">
		    		@yield('content')
		  		</div>
			</div>
		</body>
	@show

</html>
	

app/views/navbar.blade.php
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="">PiPresentation</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li>{{link_to_route('posts.index', 'Presentation')}}</li>
      <li>{{link_to_route('posts.admin', 'Administrering')}}</li>
      <li>{{link_to_route('posts.create', 'Lägg till ny')}}</li>
    </ul>
  </div>
</div>

app/views/posts/admin.blade.php
@extends('master')
@section('title', 'Redigera Poster')

@section('content')
	<table class="table table-striped table-bordered">
		@foreach (Post::all() as $index => $post)
		 <tr><td>{{$post->title}} </td>
		 	<td>{{link_to_route('posts.show', 'Visa', [$post->id])}}</td>
		 	<td>{{link_to_route('posts.edit', 'Redigera', [$post->id])}}</td>
		</tr>
		@endforeach
	</table>

	<div>
		{{ link_to_route('posts.create', "Lägg till post", [], ['class' => 'btn btn-primary pull-right']) }}
	</div>
@stop

app/views/posts/create.blade.php
@extends('master')
@section('content')
	{{ Form::open(['url' => 'posts', 'files' => true, 'method' => 'post']) }}

	@include('posts.form')

	{{ Form::submit('Skapa', array('class' => 'btn btn-primary')) }}


	{{ Form::close() }}
@stop

app/views/posts/edit.blade.php
@extends('master')
@section('title', 'Uppdatera -' . $post->title)
@section('content')
	{{ HTML::ul($errors->all()) }}
	{{ Form::model($post, array('class' => 'form-horizontal', 'role' => 'form', 'method' => 'PUT', 'route' => array('posts.update', $post->id)))}}
		@include('posts.form')
		{{ Form::submit('Uppdatera', array('class' => 'btn btn-primary')) }}
	{{ Form::close() }}

	{{Form::open(['url' => route('posts.destroy', [$post->id]), 'method' => 'delete'])}}
		{{ Form::submit('Ta bort', array('class' => 'btn btn-primary')) }}	
	{{Form::close()}}
@stop

app/views/posts/form.blade.php
<div class="form-group">
	{{ Form::label('title', 'Titel') }}
	{{ Form::text('title', null, array('class' => 'form-control')) }}
</div>

<div class="form-group">
	{{ Form::label('text', 'Text') }}
	{{ Form::textarea('text', null, array('class' => 'form-control')) }}
</div>

<div class="form-group">
	{{ Form::label('published_at', 'Publish') }}
	{{ Form::text('published_at', Carbon::now(), array('class' => 'form-control')) }}
</div>

<div class="form-group">
	{{ Form::label('expired_at', 'Expire') }}
	{{ Form::text('expired_at', Carbon::now()->addWeeks(2), array('class' => 'form-control')) }}
</div>

app/views/posts/index.blade.php
<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>@yield('title', 'Presentation')</title>

    {{ HTML::style('css/all.css') }}
    {{ HTML::style('css/pres.css') }}

    {{HTML::script(url("//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"))}}
    {{HTML::script('//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')}}

    <script type="text/javascript">
        $(document).ready(function () {
            $('#myCarousel').carousel({
                pause: 'none',
                interval: 3000
            })
        });
    </script>

</head>


<body>

<div id="background-carousel">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner text-center">
            <div class="item cal">
                <div class="container2">
                    <h1>Kalender</h1>

                    <div class="well"><? require_once('mainCalendar.php'); ?></div>
                </div>
                <div style="position: absolute; bottom: 40px; left: 0; width:100%"><p style="text-align:center">Tips!
                        Synka din kalender från tekniskfysik.se/kalender</div>
            </div>
            @foreach (Post::all() as $index => $post)
            <div class="{{$index == 0 ? " item active
            ":"item"}}" id="content-wrapper">
            <div class="container2">
                <h1>{{$post->title}}</h1>

                <div class="well">{{$post->text}}</div>
            </div>
        </div>
        @endforeach

    </div>
</div>
</div>

</body>

</html>

app/views/posts/show.blade.php
/Applications/XAMPP/xamppfiles/htdocs/pipres/app/views/posts/show.blade.php